name: Commit message output
description: 'Parsing commit message and extract values into output'
inputs:
  default:
    description: "Default value if commit message doesn't contain proper values"
    required: true
    default: 'latest'
outputs:
  tag:
    description: 'The parsed tag'
runs:
  using: 'node20'
  main: 'dist/index.js'
